name: End-to-end tests
on: 
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v5
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          # name: cypress-videos
          # path: cypress/videos
          name: mocha-report
          path: cypress/reports

# Send-Email:
#     runs-on: ubuntu-latest
#     needs: End-to-end tests
#     if: always()
#     steps:
#       - name: Checkout GitCode
#         uses: actions/checkout@v2

      - name: Download Cypress artifacts
        uses: actions/download-artifact@v2
        with:
          name: mocha-report
          path: cypress/reports

      - name: Send email with Cypress artifacts
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Cypress test results"
          from: Test Suite
          body: |
            Hi,
            The Cypress test workflow for.
            Please find the Cypress artifacts attached to this email.
            Regards,
            abc
          to: wuper.dev88@gmail.com
          attachments: |
            ./cypress-results/*.html